/* SELECIONANDO E LISTANDO NOME E MATRICULA DOS CADASTROS NA TABELA DE VENDEDORES */
SELECT NOME, MATRICULA FROM tabela_de_vendedores;

/* SELECIONANDO E LISTANDO TODOS OS CAMPOS CADASTRADOS NA TABELA DE VENDEDORES */
SELECT * FROM tabela_de_vendedores;

/* SELECIONANDO E LISTANDO APENAS OS 5 PRIMEIROS */
SELECT * FROM tabela_de_vendedores LIMIT 5;

/* SELECIONANDO E LISTANDO NOME E MATRICULA, MAS AGORA ESSE CAMPOS POSSUEM APELIDOS */
SELECT NOME AS NAME, MATRICULA AS COD FROM tabela_de_vendedores;

/* SELECIONANDO TODOS DADOS DE TODOS REGISTROS DE VENDEDORES QUE ESTÃO DE FÉRIAS */
SELECT * FROM tabela_de_vendedores WHERE DE_FERIAS = 1;

/* SELECIONANDO VENDEDORES CUJA COMISSAO É MAIOR QUE 10% OU 0.1 */
SELECT * FROM tabela_de_vendedores WHERE PERCENTUAL_COMISSAO > 0.1;

/* SELECIONANDO VENDEDORES CUJA DATA ADMISSAO FOI ANTES DO ANO 2016 */
/* USAMOS A FUNCAO YEAR QUE RECEBE UMA DATA E RETORNA O ANO EM INTEIRO */
SELECT * FROM tabela_de_vendedores WHERE YEAR(DATA_ADMISSAO) < 2016;

/* USANDO FILTO COMPOSTO! */
/* VISUALIZANDO VENDEDORES DE FÉRIAS QUE FORAM ADMITIDOS ANTES DE 2016 */
SELECT * FROM tabela_de_vendedores WHERE DE_FERIAS = 1 AND YEAR(DATA_ADMISSAO) < 2016;